[workspace]
members = ["domain", "domain-core", "domain-resolv", "domain-sign", "domain-tsig", "domain-validate", "interop"]

[patch.crates-io]
ring = { git = "https://github.com/vavrusa/ring.git", rev = "993f050c759376f918b1cfcc5bffc7a63e2f2fca"}