[package]
name = "domain-core"
version = "0.4.1"
authors = ["Martin Hoffmann <hn@nvnc.de>"]
description = "A DNS library for Rust – Core."
documentation = "https://docs.rs/domain-core/"
homepage = "https://github.com/nlnetlabs/domain/"
repository = "https://github.com/nlnetlabs/domain/"
readme = "README.md"
keywords = ["DNS", "domain"]
license = "BSD-3-Clause"

[lib]
name = "domain_core"
path = "src/lib.rs"

[features]
dnssec = ["ring", "untrusted"]
tsig = ["ring"]
default = ["tsig", "dnssec"]

[dependencies]
bytes          = "^0.4"
chrono         = "^0.4"
failure        = "^0.1"
failure_derive = "^0.1"
rand           = "^0.6"
void           = "^1.0"

[dependencies.ring]
version = "^0.14"
optional = true

[dependencies.untrusted]
version = "^0.6"
optional = true

[dev-dependencies]
base64         = "^0.10"